#!/usr/bin/env bash
# Count the number of each IP along with status code from Apache log and sort by occurrence

awk '{print $1, $9}' ./apache-access.log | sort | uniq -c | sort -k1,1nr | awk '{print $2, $3, $1}'
