#!/usr/bin/env bash
# print 20 times to print on the screen

i=1
while [ $i -le 20 ]
do
    case $i in
        4)
            echo 'bad luck from China'
            echo $i
            ;;
        9)
            echo 'bad luck from Japan'
            echo $i
            ;;
        17)
            echo 'bad luck from Italy'
            echo $i
            ;;
        *)
            echo $i
            ;;
    esac

    ((i++))
done
